database:
  db_type: "postgres"
  dsn: "host=localhost port=5432 user=salon password=yourpassword dbname=salon sslmode=disable"
  auto_migrate: true
  log:
    enabled: true
    filename: logs/sql.log
    ignore_record_not_found_error: true
    colorful: true
log:
  level: debug
  outputPaths:
    - logs/salon.log

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0
  secret: "somerandomsecret"
jwt:
  secret_key: "somerandomsecret"
  expire: "168h"

miniapp:
  wechat:
    app_id: "xxxx"
    app_secret: "aaaaaa"

server:
  address: ":9080"

static:
  domain: "http://127.0.0.1:9080"
  url_path: "static"
  enable_local: true
  static_path: "static"