database:
  db_type: "postgres"
  dsn: "host=localhost port=5432 user=salon password=yourpassword dbname=salon sslmode=disable"
  auto_migrate: true
  log:
    enabled: true
    filename: logs/sql.log
    ignore_record_not_found_error: true
    colorful: true
log:
  level: debug
  outputPaths:
    - logs/salon.log

jwt:
  secret_key: "somerandomsecret"
  expire: "168h"

miniapp:
  wechat:
    app_id: "xxxx"
    app_secret: "aaaaaa"

server:
  address: ":9080"