database:
  db_type: "postgres"
  dsn: "host=localhost port=5432 user=salon password=yourpassword dbname=salon sslmode=disable"
  auto_migrate: true
log:
  level: debug
  encoding: json
  outputPaths:
    - stdout
    - logs/salon.log
  errorOutputPaths:
    - stderr
  encoderConfig:
    messageKey: message
    levelKey: level
    timeKey: ts
    nameKey: logger
    callerKey: caller
    stacktraceKey: stacktrace
    lineEnding: ""
    levelEncoder: lowercase
    timeEncoder: iso8601
    durationEncoder: string
    callerEncoder: short
    nameEncoder: full